### ISSUE TITLE
Look into parsing the UCS .csv file. Check out DictReader

### ISSUE THREAD

**Issue by SoundsLikeJonny** [SoundsLikeJonny/UCS-Voice-Naming-Tool#41]
links:
- https://docs.python.org/3/library/csv.html#csv.DictReader
- https://realpython.com/python-csv/#what-is-a-csv-file
-https://towardsdatascience.com/five-killer-optimization-techniques-every-pandas-user-should-know-266662bd1163

**Comment by DarthTigerson** [comment]
Tag me if you run it not any issues.

**Comment by SoundsLikeJonny** [comment]
Pandas is now in use.

Thanks, @DarthTigerson !
